# Generated by Django 3.0.5 on 2021-02-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blogpost',
            new_name='Task',
        ),
    ]
