# Generated by Django 3.0.5 on 2021-02-16 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_complete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='complete',
        ),
    ]
